openapi: "3.0.2"
info:
  title: FastID
  version: 0.0.1
  license:
    name: MIT License
    url: https://choosealicense.com/licenses/mit/

paths:
  /api/v1/server/:
    get:
      tags:
        - Server
      summary: Server settings and status
      responses:
        200:
          description: Return server settings and status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ok, need_setup, locked]
                    description: >
                      Description of statuses:
                       * `ok` - The server is working fine
                       * `need_setup` - Initial server setup is required
                       * `locked` - The server is blocked and requires a key to decrypt the data
                  password_min_length:
                    type: number
                    description: Minimum password length
                  password_max_length:
                    type: number
                    description: Maximum password length
                  password_validator_url:
                    type: string
                    description: Validation link
                  email_validator_url:
                    type: string
                    description: Validation link
    post:
      tags:
        - Server
      summary: Initial server setup
      description: Creates a super user with admin accesses. And also returns the key to decrypt the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  format: password
              example:
                email: "user_admin@exmaple.com"
                password: "password"
      responses:
        201:
          description: Return server settings and status
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    description: Email address
                  username:
                    type: string
                    description: Username
                  key:
                    type: string
                    description: The key for decrypting the database
    patch:
      tags:
        - Server
      summary: Unlock database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                  description: The key for decrypting the database
      responses:
        201:
          description: Return server settings and status
          content:
            application/json:
              schema:
                type: object

  /api/v1/keys/:
    get:
      tags:
        - Keys
      summary: Verifies encryption and signature keys
      responses:
        200:
          description: "Возращает авторизационную cookie"
          content:
            application/json:
              schema:
                type: object
    post:
      tags:
        - Keys
      summary: Creates a key pair for encryption and signature
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Returns the number of keys
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string


  /api/v1/auth/:
    post:
      tags:
        - Auth
      summary: Авторизация и аунтификация
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: "admin"
                password: "password"

      responses:
        200:
          description: "Возращает авторизационную cookie"
          content:
            application/json:
              schema:
                type: object

#components:

